const API = window.PANINI_API_URL || "http://127.0.0.1:8000";
let rules = [];
const $ = (selector) => document.querySelector(selector);
const api = async (path, options = {}) => { const response = await fetch(`${API}${path}`, { headers: { "Content-Type": "application/json" }, ...options }); if (!response.ok) throw new Error((await response.json()).detail || "The grammar engine returned an error."); return response.json(); };

function ruleRow(rule, checked = true, name = "derive-rule") { return `<label class="rule-row"><input type="checkbox" name="${name}" value="${rule.rule_id}" ${checked ? "checked" : ""}><span class="rule-info"><strong>${rule.sutra} · ${rule.name}</strong><span>priority ${rule.priority} · ${rule.rule_id}</span></span></label>`; }
function selected(name) { return [...document.querySelectorAll(`input[name="${name}"]:not(:checked)`)].map((input) => input.value); }
function renderRules() { $("#rule-list").innerHTML = rules.map((rule) => ruleRow(rule)).join(""); $("#experiment-rules").innerHTML = rules.map((rule) => ruleRow(rule, false, "experiment-rule")).join(""); }
function renderTrace(trace) { $("#trace").innerHTML = trace.length ? trace.map((step) => `<div class="trace-item"><div class="trace-num">0${step.step}</div><div><strong>${step.sutra} · ${step.rule_name}</strong><small>${step.explanation}</small></div><div class="trace-surfaces">${step.before_surface} <b>→</b> ${step.after_surface}</div></div>`).join("") : `<div class="empty-state">No rule matched this surface.</div>`; }
async function derive() { const input = $("#surface").value.trim(); if (!input) return; $("#derive-btn").disabled = true; $("#result-state").textContent = "RUNNING"; try { const data = await api("/derive", { method: "POST", body: JSON.stringify({ input_surface: input, disabled_rules: selected("derive-rule") }) }); $("#result-input").textContent = data.input; $("#result-output").textContent = data.output; $("#metric-rules").textContent = data.applied_rules.length; $("#metric-steps").textContent = data.trace.length; $("#metric-halt").textContent = data.halted ? "LIMIT" : "STABLE"; $("#result-state").textContent = "COMPLETE"; renderTrace(data.trace); } catch (error) { $("#result-state").textContent = "ERROR"; $("#trace").innerHTML = `<div class="empty-state">${error.message}</div>`; } finally { $("#derive-btn").disabled = false; } }
async function experiment() { const disabled = selected("experiment-rule"); if (!disabled.length) { $("#comparison-content").innerHTML = `<div class="empty-state">Choose at least one rule to remove.</div>`; return; } try { const data = await api("/experiment", { method: "POST", body: JSON.stringify({ input_surface: $("#surface").value.trim() || "अइ", disabled_rules: disabled }) }); $("#comparison-content").innerHTML = `<div class="compare-grid"><div class="compare-card"><span>FULL GRAMMAR</span><strong>${data.baseline_output}</strong><small>${data.impact_summary.baseline_steps} steps</small></div><div class="compare-card accent"><span>WITHOUT ${disabled.join(", ")}</span><strong>${data.counterfactual_output}</strong><small>${data.impact_summary.counterfactual_steps} steps</small></div></div><div class="impact">${data.output_changed ? "The output changes when this rule is removed." : "The output is preserved under this intervention."} <b>${data.impact_summary.changed_steps} trace changes</b>.</div>`; } catch (error) { $("#comparison-content").innerHTML = `<div class="empty-state">${error.message}</div>`; } }
async function atlas() { try { const [graph, interactionData] = await Promise.all([api("/graph"), api("/interactions")]); $("#graph").innerHTML = graph.nodes.map((node, index) => `${index ? `<div class="graph-arrow">→</div>` : ""}<div class="graph-node">${node.label}<small>${node.name}</small></div>`).join(""); $("#interactions").innerHTML = (interactionData.interactions || []).map((item) => `<div class="interaction"><span>${item.source}</span><b>${item.relation.replace("_", " ")}</b><span>${item.target}</span></div>`).join("") || `<div class="empty-state">No observed interactions yet.</div>`; } catch (error) { $("#graph").innerHTML = `<div class="empty-state">${error.message}</div>`; } }
async function boot() { try { const data = await api("/rules"); rules = data.rules; renderRules(); $("#api-status").textContent = "engine online"; $(".status i").style.background = "#9bd33d"; atlas(); derive(); } catch (error) { $("#api-status").textContent = "engine offline"; $("#trace").innerHTML = `<div class="empty-state">Start the FastAPI server at ${API} to connect the lab.</div>`; } }
document.querySelectorAll(".tab").forEach((tab) => tab.addEventListener("click", () => { document.querySelectorAll(".tab").forEach((item) => item.classList.remove("active")); document.querySelectorAll(".view").forEach((view) => view.classList.remove("active-view")); tab.classList.add("active"); $(`#${tab.dataset.view}-view`).classList.add("active-view"); if (tab.dataset.view === "atlas") atlas(); }));
$("#derive-btn").addEventListener("click", derive); $("#experiment-btn").addEventListener("click", experiment); $("#surface").addEventListener("keydown", (event) => { if (event.key === "Enter") derive(); }); $("#select-all-rules").addEventListener("click", () => document.querySelectorAll('input[name="derive-rule"]').forEach((input) => { input.checked = true; })); $("#clear-rules").addEventListener("click", () => document.querySelectorAll('input[name="derive-rule"]').forEach((input) => { input.checked = false; })); document.querySelectorAll("[data-input]").forEach((button) => button.addEventListener("click", () => { $("#surface").value = button.dataset.input; derive(); })); boot();